/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilenameRouteImport } from './routes/$filename'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as FSlugRouteImport } from './routes/f/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaSlugRouteImport } from './routes/api/media/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilenameRoute = FilenameRouteImport.update({
  id: '/$filename',
  path: '/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSlugRoute = ApiMediaSlugRouteImport.update({
  id: '/api/media/$slug',
  path: '/api/media/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$filename': typeof FilenameRoute
  '/login': typeof LoginRoute
  '/api/upload': typeof ApiUploadRoute
  '/f/$slug': typeof FSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$slug': typeof ApiMediaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$filename': typeof FilenameRoute
  '/login': typeof LoginRoute
  '/api/upload': typeof ApiUploadRoute
  '/f/$slug': typeof FSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$slug': typeof ApiMediaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$filename': typeof FilenameRoute
  '/login': typeof LoginRoute
  '/api/upload': typeof ApiUploadRoute
  '/f/$slug': typeof FSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$slug': typeof ApiMediaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$filename'
    | '/login'
    | '/api/upload'
    | '/f/$slug'
    | '/api/auth/$'
    | '/api/media/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$filename'
    | '/login'
    | '/api/upload'
    | '/f/$slug'
    | '/api/auth/$'
    | '/api/media/$slug'
  id:
    | '__root__'
    | '/'
    | '/$filename'
    | '/login'
    | '/api/upload'
    | '/f/$slug'
    | '/api/auth/$'
    | '/api/media/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilenameRoute: typeof FilenameRoute
  LoginRoute: typeof LoginRoute
  ApiUploadRoute: typeof ApiUploadRoute
  FSlugRoute: typeof FSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaSlugRoute: typeof ApiMediaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$filename': {
      id: '/$filename'
      path: '/$filename'
      fullPath: '/$filename'
      preLoaderRoute: typeof FilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$slug': {
      id: '/api/media/$slug'
      path: '/api/media/$slug'
      fullPath: '/api/media/$slug'
      preLoaderRoute: typeof ApiMediaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilenameRoute: FilenameRoute,
  LoginRoute: LoginRoute,
  ApiUploadRoute: ApiUploadRoute,
  FSlugRoute: FSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaSlugRoute: ApiMediaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
